namespace EndfieldChargePlus;

public static partial class LocalizationManager
{
    private static void AddFeatureTranslations(Dictionary<string,string> items)
    {
        var features=new Dictionary<string,string>
        {
            ["貼上你自己的 Gemini API Key"]="Paste your own Gemini API key",
            ["目前上限以以下用量顯示為準。同一金鑰保留已核對的限制與今日用量；儲存及套用不呼叫 Google。"]="Current limits are shown in the usage status below. The same key keeps its verified limits and today's usage; saving and applying do not call Google.",
            ["首次設定／更換金鑰的限制說明"]="Limits for first setup or a different key",
            ["只有首次設定或更換不同金鑰，才預設採本機 20 次／日、3 次／分鐘的保守限制；這不是 Google 的實際額度。原本已核對的同一金鑰不會被降低。套用會重新啟動共用 AI 服務。"]="Only first setup or a different key starts with conservative local caps of 20 requests/day and 3/minute. These are not Google's actual quota. The same verified key is not downgraded. Applying restarts the shared AI service.",
            ["我已確認此金鑰的專案使用免費方案，且未啟用付費。"]="I confirmed this key's project uses the free tier with billing disabled.",
            ["新金鑰預設本機上限 20 次／日、3 次／分鐘；這不是 Google 實際剩餘額度。既有同一金鑰的限制與用量保留。套用會重新啟動共用 AI 服務，設定過程不呼叫 Google。"]="New keys start with local limits of 20 requests/day and 3/minute, not Google's actual remaining quota. Existing limits and usage for the same key are kept. Applying restarts the shared AI service without calling Google.",
            ["桌面控制中心"]="Desktop control center",
            ["本機工作站 · 搜尋 / 音樂 / 提醒"]="Local workstation · Search / Music / Reminders",
            ["AI 助理"]="AI Assistant",
            ["靈動島 AI 助理"]="Island AI Assistant",
            ["開啟 AI 靈動島   Alt+A"]="Open AI Island   Alt+A",
            ["Alt+A 喚出並輸入 · Enter 送出 · Shift+Enter 換行\n文字先向左右延伸，再換行向下延伸。長回覆可捲動。\n點島的本體標頭可收起；輸入、選取回覆與來源按鈕保持可操作。右鍵可開新對話."]="Alt+A opens and focuses input · Enter sends · Shift+Enter adds a line.\nThe island expands, then wraps. Long replies can be scrolled.\nClick the header to retract; right-click for a new conversation.",
            ["Alt+A 喚出並輸入 · Enter 送出 · Shift+Enter 換行\n文字先向左右延伸，再換行向下延伸。長回覆可捲動。\n點島的本體標頭可收起；輸入、選取回覆與來源按鈕保持可操作。右鍵可開新對話。"]="Alt+A opens and focuses input · Enter sends · Shift+Enter adds a line.\nThe island expands, then wraps. Long replies can be scrolled.\nClick the header to retract; right-click for a new conversation.",
            ["金鑰只加密保存在這台電腦。儲存不扣 AI 次數；不會顯示已儲存的金鑰。"]="Your key is encrypted on this PC. Saving does not spend AI requests or reveal the saved key.",
            ["貼上目前已核對專案的 API Key"]="Paste the key for your verified project",
            ["儲存並套用金鑰"]="Save & apply key",
            ["套用會重新啟動共用 AI 服務。每日額度與免費方案核對紀錄保留；其他專案須先核對方案與額度。"]="Applying restarts the shared AI service. Daily usage and free-tier verification are retained; verify a different project's limits first.",
            ["正在查詢本機 AI 狀態…"]="Checking local AI status…",
            ["查詢用量"]="Check usage",
            ["一般聊天使用 Gemini 3.5 Flash Lite；最新資訊先使用 XNG 共用搜尋。\n「只搜尋」不呼叫 Gemini。未設定 Key 或用量鎖定時，仍能取得 XNG 搜尋證據。\n對話以 Windows 使用者加密保存在本機；收起不會清空，右鍵新對話才重設。\n長對話會選取最近內容及相關舊對話節錄；不代表每次都送出全部歷史。"]="Chat uses Gemini 3.5 Flash Lite; current information goes through shared XNG search first.\nSearch only does not call Gemini and works without a key or while usage is locked.\nChats are encrypted locally for your Windows user. Retracting keeps them; New conversation resets them.\nLong conversations use recent turns and relevant excerpts, rather than sending the entire history.",
            ["對話頭像"]="Chat avatars",
            ["選擇本機圖片。你的頭像使用黃色外圈，AI 維持青藍色外圈；圖片只保存在這台電腦，不上傳。"]="Choose local images. Your avatar has a yellow ring; the AI avatar keeps its cyan ring. Images stay on this PC and are never uploaded.",
            ["設定我的大頭照"]="My avatar",["設定 AI 大頭照"]="AI avatar",["還原預設頭像"]="Reset avatars",
            ["PNG / JPEG / WebP · 自動置中裁成圓形"]="PNG / JPEG / WebP · Centered circular crop",
            ["Windows 通知"]="Windows Notifications",["Windows 通知顯示器"]="Windows Notification Display",
            ["啟用 Windows 通知靈動島"]="Enable notification island",["隱藏通知內容（僅顯示來源）"]="Hide notification contents (source only)",
            ["新通知優先顯示，結束後回到上一頁。點本體固定，再點收起；滑鼠停在島上時不會逾時。\n最多保留 10 則、2 分鐘。收起卡片不會刪除 Windows 通知。"]="New notifications take priority, then return to your previous page. Click to pin, click again to hide; hovering holds the timeout.\nThe queue holds 10 items for up to 2 minutes. Hiding a card does not delete the Windows notification.",
            ["預覽時間沿用「大小與動畫」的顯示秒數。設定需按「儲存並套用」。\n通知只留在本機記憶體，不傳給 Gemini / XNG，不建立通知歷史檔案。啟動或重新啟用時不重播舊通知。"]="Preview uses the duration under Size & Animation. Save & Apply to keep your settings.\nNotifications stay in local memory, never go to Gemini/XNG, and are not archived. Old notifications are not replayed at startup.",
            ["正在檢查通知權限…"]="Checking notification access…",["要求通知讀取權限"]="Request notification access",
            ["送出 Windows 測試通知"]="Send Windows test notification",["預覽通知介面"]="Preview notification",
            ["Windows 的通知或勿擾設定可能影響通知是否產生。測試按鈕會提交本程式的 Windows 通知；通知權限由 Windows 管理。\n「預覽通知介面」只產生本機示範卡片，不代表已成功讀取系統通知。"]="Windows notification and Do Not Disturb settings affect delivery. The test submits this app's notification; Windows manages access.\nPreview creates a local sample card and does not prove system notifications can be read.",
            ["音樂播放"]="Music",["播放清單"]="Playlist",["儲存播放清單"]="Save playlist",["開啟指定播放清單"]="Open saved playlist",
            ["音樂"]="Music",["YouTube 音樂播放清單"]="YouTube music playlist",
            ["貼上指定播放清單網址。專用背景播放器載入 YouTube 原頁，音樂島可直接控制播放、進度、隨機與重播，不受 Windows 媒體接口缺少功能的限制。"]="Paste your playlist URL. A dedicated background player loads the original YouTube page, enabling playback, seek, shuffle, and repeat from the island.",
            ["儲存清單"]="Save playlist",["啟動背景清單並顯示音樂島"]="Start playlist & open island",["跟隨目前瀏覽器播放"]="Follow current browser",["顯示音樂島 Alt+M"]="Show music island Alt+M",
            ["兩種模式獨立：清單只控制專用播放器；網頁只跟隨 Windows 瀏覽器媒體。切到網頁會關閉清單播放器。Alt+M 保留目前模式。"]="Modes are separate: Playlist controls its dedicated player; Browser follows Windows browser media. Switching to Browser closes the playlist player. Alt+M keeps the current mode.",
            ["Alt+M 顯示音樂島；點封面啟動清單，點曲名區收起，右鍵切換播放清單／跟隨瀏覽器模式或設定清單。Alt+A 可切回 AI 對話。重播依序切換：關／整份清單／單曲。YouTube 播放限制與登入要求仍需在原頁處理。"]="Alt+M opens the music island. Click cover to start the playlist, click the title to retract, or right-click to choose mode/settings. Alt+A returns to AI. Repeat cycles Off / Playlist / Track. Handle YouTube playback restrictions and sign-in on the original page.",
            ["範本支援 {變數|格式}；進階運算式使用 {= 運算式 | 格式}，支援 + - * / % ^、比較、&& / || / !、?:、??、if()、min/max/avg/sum/clamp/round 等；進度變數也可填寫 = 運算式。例：{= if(memory.usage >= 80, '高', '正常')}。"]="Templates use {variable|format}. Expressions use {= expression | format}, with arithmetic, comparisons, logical operators, if(), min/max/avg/sum/clamp/round. Example: {= if(memory.usage >= 80, 'High', 'OK')}.",
            ["YouTube 播放清單網址"]="YouTube playlist URL",["播放进度"]="Playback progress",
            ["播放清單網址"]="Playlist URL",["跟隨瀏覽器播放"]="Follow browser playback",["顯示音樂靈動島"]="Show music island",
            ["播放清單已儲存。"]="Playlist saved.",["既有清單設定無法讀取，未覆寫："]="Existing playlist could not be read; preserved: ",
            ["Endfield AI 靈動島"]="Endfield AI Island",["點標頭收起 · 右鍵新對話"]="Click header to retract · Right-click for a new chat",
            ["新對話"]="New conversation",["記憶宮殿／定時提醒"]="Memory palace / Reminders",["查詢 Gemini 用量"]="Check Gemini usage",
            ["查詢 XNG 插件版本"]="Check XNG plugin version",["管理 XNG 插件／來源規則"]="Manage XNG plugin / Source rules",
            ["收起靈動島"]="Retract island",["輸入訊息… Enter 送出"]="Type a message… Enter to send",
            ["Alt+A 喚出 · Shift+Enter 換行"]="Alt+A to open · Shift+Enter for a new line",
            ["自動"]="Auto",["只聊天"]="Chat only",["只搜尋"]="Search only",["搜尋＋AI"]="Search + AI",["送出"]="Send",["取消"]="Cancel",
            ["本機提醒／記憶 · 未使用 Gemini 額度"]="Local reminders / Memory · No Gemini requests used",
            ["Gemini 3.5 Lite 思考中…"]="Gemini 3.5 Lite is thinking…",["取得共用搜尋與 AI 回覆…"]="Getting shared search evidence and AI response…",
            ["Gemini 3.5 Lite · 對話已保留"]="Gemini 3.5 Lite · Conversation saved",["XNG 免費搜尋證據 · 未產生 Gemini 回答"]="Free XNG evidence · No Gemini answer generated",
            ["AI 共用服務尚未連線 · Alt+A 喚出 · 右鍵新對話"]="Shared AI service is offline · Alt+A to open · Right-click for a new chat",
            ["正在查詢 XNG 插件版本…"]="Checking XNG plugin version…",["無法查詢 XNG；請確認共用 AI 服務已啟動。"]="XNG status is unavailable. Start the shared AI service.",
            ["無法連線至共用 AI 服務。請先啟動 Gemini Hub（8890）。"]="Cannot connect to the shared AI service. Start Gemini Hub (8890).",
            ["本次已取消；已送達 Gemini 的請求仍可能計入額度。"]="Cancelled. Requests already delivered to Gemini may still count toward usage.",
            [" · 最舊內容已超過本機儲存上限"]=" · Oldest messages exceeded the local storage limit",
            ["音樂靈動島"]="Music Island",["播放清單模式"]="Playlist mode",["跟隨瀏覽器模式"]="Follow browser mode",
            ["在瀏覽器開啟清單並跟隨"]="Open playlist in browser and follow",["設定播放清單"]="Playlist settings",["收起音樂島"]="Retract music island",
            ["播放清單模式 · 背景播放器正在載入指定清單"]="Playlist mode · Loading saved playlist in background",
            ["無法開啟清單："]="Cannot open playlist: ",["正在切換音樂來源"]="Switching music source",["等待目前模式的播放資訊"]="Waiting for the selected source",
            ["Windows 媒體資訊暫時無法讀取；可從瀏覽器控制播放"]="Windows media information is unavailable. Control playback in the browser.",
            ["已送出播放控制"]="Playback command sent",["此模式未支援此控制；請從播放器操作"]="This mode does not support that control. Use the player.",
            ["播放控制失敗；請從播放器重試"]="Playback command failed. Try in the player.",
            ["隨機播放：開"]="Shuffle: on",["隨機播放：關"]="Shuffle: off",["隨機播放"]="Shuffle",["上一首"]="Previous",["下一首"]="Next",
            ["播放或暫停"]="Play or pause",["播放／暫停"]="Play / Pause",["重播"]="Repeat",["重播：關／清單／單曲"]="Repeat: off / Playlist / Track",
            ["此瀏覽器未提供隨機控制；請在 YouTube 原頁切換"]="This browser does not expose shuffle. Change it on YouTube.",
            ["此瀏覽器未提供重播控制；請在 YouTube 原頁切換"]="This browser does not expose repeat. Change it on YouTube.",
            ["點封面啟動播放清單"]="Click cover to start playlist",["YouTube / 背景音樂"]="YouTube / Background music",
            ["點封面啟動指定清單；右鍵可設定清單"]="Click cover to start saved playlist; right-click for settings",
            ["點曲名區收起 · 右鍵設定播放清單"]="Click title to retract · Right-click for playlist settings",
            ["Alt+M · 右鍵設定清單"]="Alt+M · Right-click for playlist settings",["音樂清單設定"]="Music playlist settings",
            ["通知顯示器尚未就緒"]="Notification display is not ready",["通知顯示器正在初始化"]="Initializing notification display",
            ["通知顯示器已關閉"]="Notification display is closed",["Windows 已允許通知讀取"]="Windows notification access is allowed",
            ["無法要求通知讀取權限，請稍後重試"]="Notification access request failed. Try again later.",
            ["請先收起目前的通知或等待切換完成，再預覽通知介面"]="Hide the current notification or wait for the transition before previewing.",
            ["正在顯示本機示範卡片；這不代表已讀取 Windows 通知"]="Showing a local sample card; this does not prove Windows notification access.",
            ["通知介面預覽失敗，請稍後重試"]="Notification preview failed. Try again later.",
            ["已固定 · 再點收起"]="Pinned · Click again to hide",["停留中 · 移開後收起"]="Held · Move away to dismiss",
            ["收到新通知"]="New notification",["內容已隱藏；請從 Windows 通知中心查看"]="Contents hidden. View in Windows Notification Center.",
            ["通知顯示已停用"]="Notification display is disabled",["已連接 Windows 通知 · 只顯示新通知"]="Windows notifications connected · New items only",
            ["正在讀取 Windows 通知…"]="Reading Windows notifications…",["Windows 已拒絕通知讀取權限；請在 Windows 設定調整"]="Windows denied notification access. Adjust it in Windows settings.",
            ["此 Windows 環境暫時無法使用通知讀取 API"]="Notification access is unavailable in this Windows environment",
            ["尚未授權；請按「要求通知讀取權限」"]="Access not granted. Select Request notification access.",
            ["記憶宮殿與定時提醒"]="Memory palace and reminders",["記憶宮殿"]="Memory palace",["個人記憶"]="Personal memory",["定時提醒"]="Reminders",
            ["身分資料"]="Identity",["喜好偏好"]="Preferences",["回答方式"]="Response style",["互動禁忌"]="Interaction boundaries",
            ["生活習慣"]="Habits",["個人事項"]="Personal tasks",["目標計畫"]="Goals & plans",
            ["保存你的身分、偏好與交代事項。閒聊與假設不當成個人事實；可逐筆修改或刪除。\n僅選取背景提供給 Gemini 對話；提醒在本機執行，不呼叫模型。刪除記憶不會刪掉聊天紀錄；若不想沿用舊聊天內容，請開新對話。"]="Keep identity, preferences, and tasks. Casual chat and hypothetical claims are not personal facts. Edit or delete each record.\nSelected context goes to Gemini; reminders run locally without model calls. Deleting memory does not erase chat history. Start a new conversation to stop using old chat context.",
            ["目前沒有內容"]="No records yet",["儲存修改"]="Save changes",["刪除此記憶"]="Delete memory",["刪除此提醒"]="Delete reminder",
            ["提醒事項"]="Reminder task",["提醒時間（本機時區）"]="Reminder time (local time zone)",["修改並重新排程"]="Save & reschedule",
            ["已儲存。"]="Saved.",["資料已更新；保留你的編輯草稿，請儲存修改。"]="Records changed. Your edit draft is preserved; save your changes.",
            ["軟體運行時提醒；睡眠／關機期間不響，回來後補顯示逾期事項。最多 300 筆，滿額依建立順序移除最舊提醒並取消排程。提醒只在本機，不同步 Windows 行事曆。"]="Reminders run while the app is open. After sleep or shutdown, overdue tasks are shown when you return. Up to 300 reminders; reaching capacity removes and cancels the oldest created item. Local only; no Windows calendar sync.",
            ["尚未建立提醒。對助理說：明天上午九點提醒我開會。"]="No reminders yet. Tell the assistant: 明天上午九點提醒我開會 (remind me of a meeting tomorrow at 9 AM).",
            ["時間格式請填 yyyy/MM/dd HH:mm。"]="Enter time as yyyy/MM/dd HH:mm.",
            ["圖標：Yue-plus/endfield_icons · MIT · © 2023 Yue_plus"]="Icons: Yue-plus/endfield_icons · MIT · © 2023 Yue_plus",
            ["你在記憶宮殿修改"]="Edited in memory palace",["你明確要求記住"]="Explicit memory request",["你在對話中明確自述"]="Explicit personal statement",
            ["正在加密儲存並套用…"]="Encrypting and applying…",["金鑰已加密儲存並套用；沒有發出 AI 請求。"]="Key encrypted and applied. No AI request was sent.",
            ["套用未完成，請稍後再試；每日額度保留。"]="Apply did not finish. Try again later; daily usage is preserved.",
            ["尚未設定 Gemini。請在設定 → AI 助理輸入 API Key；也可切換「只搜尋」。"]="Gemini is not configured. Enter the key in Settings → AI Assistant, or use Search only.",
            ["免費方案驗證已到期，Gemini 已鎖定；XNG 搜尋仍可使用。"]="Free-tier verification expired. Gemini is locked; XNG search remains available.",
            ["今日 Gemini 本機用量已達上限；可切換「只搜尋」。"]="Today's local Gemini usage limit was reached. Use Search only.",
            ["Gemini 本分鐘已達上限，請稍後再送出。"]="Gemini's per-minute limit was reached. Try again shortly.",
            ["這次內容超過上下文上限，請縮短訊息或開新對話。"]="Context limit exceeded. Shorten your message or start a new conversation.",
            ["共用 AI 服務正在處理其他請求，請稍後再試。"]="The shared AI service is busy. Try again shortly.",
            ["Gemini 用量保護已鎖定；可繼續使用 XNG 搜尋。"]="Gemini usage protection is locked. XNG search remains available.",
            ["本機 AI 服務驗證失敗，請確認 Gemini Hub 設定。"]="Local AI authentication failed. Check Gemini Hub settings.",
            ["共用 AI 服務目前無法完成請求。請確認 Gemini Hub 已啟動，或稍後再試。"]="The shared AI service cannot complete the request. Start Gemini Hub or try again later.",
        };
        foreach(var pair in features)items[pair.Key]=pair.Value;
    }
}
